### ISSUE TITLE
Change Public List title

### ISSUE THREAD

**Issue by Aleolly** [Aleolly/ServiisSiteIssues#2]
Public List page title should be: "Best #service_name# in #city#"

@CurlyGiac Write here Arabic translation for that string

**Comment by CurlyGiac** [comment]
"CITY"  في "SERVICE NAME" افضل

Ovviamente da dx a sx

**Comment by CurlyGiac** [comment]
Ale puoi chiudere anche questo pls

**Comment by Aleolly** [comment]
Sorry but we can't use that title format. Featured Services are multi-city and multi-services lists.
We can use the title field.

**Comment by CurlyGiac** [comment]
Let's use the name of the service that is selected then.

**Comment by Aleolly** [comment]
Not deployed yet.
