### ISSUE TITLE
Featured Services

### ISSUE THREAD

**Issue by CurlyGiac** [Aleolly/ServiisSiteIssues#4]
We want that when a user click on a featured service (bottom of the homepage) the result page only shows users with a nice complete profile. 
So the idea is to show in the result page only Pros that have a 100% profile completion.

In this way we can use this section also as an incentive to tell Pros "Complete your profile and it will be listed in the featured services section which is publicly accessible"

**Comment by Aleolly** [comment]
@CurlyGiac we have to load "featured" users I guess. 
You opened an Admin issue about featured checkbox on professionals users, in order to list them on featured services, isn't it?

**Comment by CurlyGiac** [comment]
Yes, we want to have to possibility to choose the pros that will be shown on the result page of featured services, so that we can select only those that have a proper profile. So on the pro profile (admin) ther should be a thick to make a pro visible in that section.

**Comment by Aleolly** [comment]
not deployed yet
