### ISSUE TITLE
Pro Profiles SEO

### ISSUE THREAD

**Issue by CurlyGiac** [Aleolly/ServiisSiteIssues#7]
We need to have the pro profiles listed by Google and Search Engines. Now they are not ranked. The relevant keywords should be the city of the profile, the services, and the name of the pro.

**Comment by Aleolly** [comment]
You can edit and translate seo template for all profile users, search for ''professional/##user_id##" in admin seo section.

Wait for updated admin and website deploy.

Done but not deployed yet
