### ISSUE TITLE
Public pro profile button

### ISSUE THREAD

**Issue by CurlyGiac** [Aleolly/ServiisSiteIssues#8]
In the public pro profile there is the wrong button ASK REVIEWS. It should be ASK A QUOTE and it should open a popup with the services of the pro so that the customer can select the service he needs. Then a normal request flow is initiated (request sent to all pros)

**Comment by Aleolly** [comment]
I can see the right button on that page. Are you sure you weren't looking your own profile?

**Comment by Aleolly** [comment]
@CurlyGiac check this so we can close the issue

**Comment by Aleolly** [comment]
That’s your own profile, so you got correcltly “ask review”
